services:
  web:
    image: lennyprocolibri/django-web:latest
    container_name: django_web
    command: >
      sh -c "
        echo 'Running migrations...' &&
        python manage.py migrate --noinput &&
        echo 'Collecting static files...' &&
        python manage.py collectstatic --noinput &&
        echo 'Starting Gunicorn...' &&
        gunicorn e_commerce_project.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=lennypro.com,www.lennypro.com
      - LETSENCRYPT_HOST=lennypro.com,www.lennypro.com
      - LETSENCRYPT_EMAIL=colibrifestivalca@gmail.com
      - VIRTUAL_PORT=8000
      - FORCE_SSL=true
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - nginx-proxy
      - letsencrypt
      - redis
    networks:
      - webnet

  worker:
    image: lennyprocolibri/django-web:latest
    command: >
      sh -c "
        echo 'Starting Celery worker...' &&
        celery -A e_commerce_project worker --loglevel=info --concurrency=3 --hostname=worker@%h
      "
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - webnet

  nginx-proxy:
    image: jwilder/nginx-proxy:1.8
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx_proxy
      DEFAULT_EMAIL: colibrifestivalca@gmail.com
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - webnet

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
